// Base de datos de atajos (convención Windows/Linux; en Mac ⌘ cuenta como Ctrl).
// keys: combinación principal. alt: combinaciones alternativas que también se aceptan.

const APPS = {
  windows:   { name: "Windows",   icon: "🪟", cat: "Sistema",      color: "#3A8DFF" },
  chrome:    { name: "Navegador", icon: "🌐", cat: "Internet",     color: "#FFB020" },
  vscode:    { name: "VS Code",   icon: "🧑‍💻", cat: "Programación", color: "#2D9CDB" },
  terminal:  { name: "Terminal",  icon: "🖥️", cat: "Programación", color: "#3BD16F" },
  word:      { name: "Word",      icon: "📝", cat: "Ofimática",    color: "#2B6BE0" },
  excel:     { name: "Excel",     icon: "📊", cat: "Ofimática",    color: "#1E9E57" },
  photoshop: { name: "Photoshop", icon: "🎨", cat: "Diseño",       color: "#2FA3FF" },
  figma:     { name: "Figma",     icon: "✏️", cat: "Diseño",       color: "#A259FF" },
  discord:   { name: "Discord",   icon: "🎧", cat: "Comunicación", color: "#5865F2" },
  gmail:     { name: "Gmail",     icon: "✉️", cat: "Comunicación", color: "#EA4335" },
  youtube:   { name: "YouTube",   icon: "▶️", cat: "Multimedia",   color: "#FF2D2D" },
};

const SHORTCUTS = [
  // ---- Generales / Windows ----
  { app: "windows", action: "Copiar", keys: ["Ctrl", "C"] },
  { app: "windows", action: "Pegar", keys: ["Ctrl", "V"] },
  { app: "windows", action: "Cortar", keys: ["Ctrl", "X"] },
  { app: "windows", action: "Deshacer", keys: ["Ctrl", "Z"] },
  { app: "windows", action: "Rehacer", keys: ["Ctrl", "Y"], alt: [["Ctrl", "Shift", "Z"]] },
  { app: "windows", action: "Seleccionar todo", keys: ["Ctrl", "A"] },
  { app: "windows", action: "Guardar", keys: ["Ctrl", "S"] },
  { app: "windows", action: "Buscar en la página o documento", keys: ["Ctrl", "F"] },
  { app: "windows", action: "Imprimir", keys: ["Ctrl", "P"] },
  { app: "windows", action: "Cerrar la ventana activa", keys: ["Alt", "F4"] },
  { app: "windows", action: "Cambiar entre ventanas abiertas", keys: ["Alt", "Tab"] },
  { app: "windows", action: "Mostrar el escritorio", keys: ["Win", "D"] },
  { app: "windows", action: "Bloquear el equipo", keys: ["Win", "L"] },
  { app: "windows", action: "Abrir el Explorador de archivos", keys: ["Win", "E"] },
  { app: "windows", action: "Recortar una captura de pantalla", keys: ["Win", "Shift", "S"] },
  { app: "windows", action: "Abrir el Administrador de tareas", keys: ["Ctrl", "Shift", "Esc"] },
  { app: "windows", action: "Ver el historial del portapapeles", keys: ["Win", "V"] },
  { app: "windows", action: "Abrir el panel de emojis", keys: ["Win", "."], alt: [["Win", ";"]] },
  { app: "windows", action: "Abrir Configuración", keys: ["Win", "I"] },
  { app: "windows", action: "Abrir el cuadro Ejecutar", keys: ["Win", "R"] },
  { app: "windows", action: "Renombrar el archivo seleccionado", keys: ["F2"] },
  { app: "windows", action: "Ver propiedades del archivo", keys: ["Alt", "Enter"] },
  { app: "windows", action: "Crear un escritorio virtual nuevo", keys: ["Ctrl", "Win", "D"] },
  { app: "windows", action: "Maximizar la ventana", keys: ["Win", "↑"] },
  { app: "windows", action: "Anclar la ventana a la izquierda", keys: ["Win", "←"] },
  { app: "windows", action: "Eliminar sin pasar por la papelera", keys: ["Shift", "Delete"] },
  { app: "windows", action: "Abrir la búsqueda de Windows", keys: ["Win", "S"] },
  { app: "windows", action: "Proyectar en otra pantalla", keys: ["Win", "P"] },
  { app: "windows", action: "Abrir la Xbox Game Bar", keys: ["Win", "G"] },
  { app: "windows", action: "Abrir el menú Inicio", keys: ["Win"], alt: [["Ctrl", "Esc"]] },
  { app: "windows", action: "Captura de pantalla completa guardada", keys: ["Win", "PrtSc"] },
  { app: "windows", action: "Minimizar todas las ventanas", keys: ["Win", "M"] },

  // ---- Navegador ----
  { app: "chrome", action: "Abrir una pestaña nueva", keys: ["Ctrl", "T"] },
  { app: "chrome", action: "Reabrir la última pestaña cerrada", keys: ["Ctrl", "Shift", "T"] },
  { app: "chrome", action: "Cerrar la pestaña actual", keys: ["Ctrl", "W"], alt: [["Ctrl", "F4"]] },
  { app: "chrome", action: "Abrir una ventana de incógnito", keys: ["Ctrl", "Shift", "N"] },
  { app: "chrome", action: "Ir a la pestaña siguiente", keys: ["Ctrl", "Tab"], alt: [["Ctrl", "PgDn"]] },
  { app: "chrome", action: "Recargar ignorando la caché", keys: ["Ctrl", "Shift", "R"], alt: [["Ctrl", "F5"]] },
  { app: "chrome", action: "Abrir las herramientas para desarrolladores", keys: ["F12"], alt: [["Ctrl", "Shift", "I"]] },
  { app: "chrome", action: "Ver el historial", keys: ["Ctrl", "H"] },
  { app: "chrome", action: "Ver las descargas", keys: ["Ctrl", "J"] },
  { app: "chrome", action: "Seleccionar la barra de direcciones", keys: ["Ctrl", "L"], alt: [["Alt", "D"], ["F6"]] },
  { app: "chrome", action: "Guardar la página en marcadores", keys: ["Ctrl", "D"] },
  { app: "chrome", action: "Pantalla completa", keys: ["F11"] },
  { app: "chrome", action: "Restablecer el zoom", keys: ["Ctrl", "0"] },
  { app: "chrome", action: "Saltar a la última pestaña", keys: ["Ctrl", "9"] },
  { app: "chrome", action: "Ver el código fuente de la página", keys: ["Ctrl", "U"] },
  { app: "chrome", action: "Recargar la página", keys: ["F5"], alt: [["Ctrl", "R"]] },
  { app: "chrome", action: "Volver a la página anterior", keys: ["Alt", "←"] },

  // ---- VS Code ----
  { app: "vscode", action: "Abrir la paleta de comandos", keys: ["Ctrl", "Shift", "P"], alt: [["F1"]] },
  { app: "vscode", action: "Abrir un archivo rápidamente", keys: ["Ctrl", "P"] },
  { app: "vscode", action: "Comentar / descomentar la línea", keys: ["Ctrl", "/"] },
  { app: "vscode", action: "Mostrar la terminal integrada", keys: ["Ctrl", "`"] },
  { app: "vscode", action: "Mover la línea hacia arriba", keys: ["Alt", "↑"] },
  { app: "vscode", action: "Duplicar la línea hacia abajo", keys: ["Shift", "Alt", "↓"] },
  { app: "vscode", action: "Seleccionar la siguiente coincidencia", keys: ["Ctrl", "D"] },
  { app: "vscode", action: "Formatear el documento", keys: ["Shift", "Alt", "F"] },
  { app: "vscode", action: "Ir a la definición", keys: ["F12"] },
  { app: "vscode", action: "Renombrar un símbolo", keys: ["F2"] },
  { app: "vscode", action: "Mostrar / ocultar la barra lateral", keys: ["Ctrl", "B"] },
  { app: "vscode", action: "Añadir un cursor en la línea de arriba", keys: ["Ctrl", "Alt", "↑"] },
  { app: "vscode", action: "Eliminar la línea completa", keys: ["Ctrl", "Shift", "K"] },
  { app: "vscode", action: "Ir a una línea concreta", keys: ["Ctrl", "G"] },
  { app: "vscode", action: "Buscar en todos los archivos", keys: ["Ctrl", "Shift", "F"] },
  { app: "vscode", action: "Dividir el editor", keys: ["Ctrl", "\\"] },

  // ---- Terminal ----
  { app: "terminal", action: "Interrumpir el proceso en ejecución", keys: ["Ctrl", "C"] },
  { app: "terminal", action: "Limpiar la pantalla", keys: ["Ctrl", "L"] },
  { app: "terminal", action: "Buscar en el historial de comandos", keys: ["Ctrl", "R"] },
  { app: "terminal", action: "Ir al inicio de la línea", keys: ["Ctrl", "A"], alt: [["Home"]] },
  { app: "terminal", action: "Enviar fin de archivo (EOF) / salir", keys: ["Ctrl", "D"] },
  { app: "terminal", action: "Autocompletar el comando", keys: ["Tab"] },
  { app: "terminal", action: "Suspender el proceso", keys: ["Ctrl", "Z"] },
  { app: "terminal", action: "Borrar la palabra anterior", keys: ["Ctrl", "W"] },

  // ---- Word ----
  { app: "word", action: "Poner el texto en negrita", keys: ["Ctrl", "B"], alt: [["Ctrl", "N"]] },
  { app: "word", action: "Poner el texto en cursiva", keys: ["Ctrl", "I"], alt: [["Ctrl", "K"]] },
  { app: "word", action: "Subrayar el texto", keys: ["Ctrl", "U"], alt: [["Ctrl", "S"]] },
  { app: "word", action: "Centrar el párrafo", keys: ["Ctrl", "E"], alt: [["Ctrl", "T"]] },
  { app: "word", action: "Justificar el párrafo", keys: ["Ctrl", "J"] },
  { app: "word", action: "Insertar un salto de página", keys: ["Ctrl", "Enter"] },
  { app: "word", action: "Aumentar el tamaño de la fuente", keys: ["Ctrl", "Shift", "."], alt: [["Ctrl", "]"]] },
  { app: "word", action: "Revisar la ortografía", keys: ["F7"] },
  { app: "word", action: "Alternar mayúsculas / minúsculas", keys: ["Shift", "F3"] },

  // ---- Excel ----
  { app: "excel", action: "Insertar la fecha de hoy", keys: ["Ctrl", ";"] },
  { app: "excel", action: "Autosuma", keys: ["Alt", "="] },
  { app: "excel", action: "Editar la celda activa", keys: ["F2"] },
  { app: "excel", action: "Crear una tabla", keys: ["Ctrl", "T"], alt: [["Ctrl", "Q"]] },
  { app: "excel", action: "Ocultar las filas seleccionadas", keys: ["Ctrl", "9"] },
  { app: "excel", action: "Saltar al final de los datos hacia abajo", keys: ["Ctrl", "↓"] },
  { app: "excel", action: "Abrir Formato de celdas", keys: ["Ctrl", "1"] },
  { app: "excel", action: "Fijar referencia absoluta ($A$1)", keys: ["F4"] },
  { app: "excel", action: "Insertar una hoja nueva", keys: ["Shift", "F11"] },
  { app: "excel", action: "Insertar un hipervínculo", keys: ["Ctrl", "K"] },
  { app: "excel", action: "Activar / desactivar filtros", keys: ["Ctrl", "Shift", "L"] },

  // ---- Photoshop ----
  { app: "photoshop", action: "Transformación libre", keys: ["Ctrl", "T"] },
  { app: "photoshop", action: "Crear una capa nueva", keys: ["Ctrl", "Shift", "N"] },
  { app: "photoshop", action: "Deseleccionar", keys: ["Ctrl", "D"] },
  { app: "photoshop", action: "Invertir la selección", keys: ["Ctrl", "Shift", "I"] },
  { app: "photoshop", action: "Duplicar la capa", keys: ["Ctrl", "J"] },
  { app: "photoshop", action: "Herramienta Pincel", keys: ["B"] },
  { app: "photoshop", action: "Herramienta Mover", keys: ["V"] },
  { app: "photoshop", action: "Ajustar la imagen a la pantalla", keys: ["Ctrl", "0"] },
  { app: "photoshop", action: "Combinar las capas visibles", keys: ["Ctrl", "Shift", "E"] },

  // ---- Figma ----
  { app: "figma", action: "Agrupar la selección", keys: ["Ctrl", "G"] },
  { app: "figma", action: "Crear un componente", keys: ["Ctrl", "Alt", "K"] },
  { app: "figma", action: "Añadir Auto layout", keys: ["Shift", "A"] },
  { app: "figma", action: "Herramienta Rectángulo", keys: ["R"] },
  { app: "figma", action: "Mostrar / ocultar la interfaz", keys: ["Ctrl", "\\"] },
  { app: "figma", action: "Zoom para ver todo", keys: ["Shift", "1"] },
  { app: "figma", action: "Herramienta Texto", keys: ["T"] },

  // ---- Discord ----
  { app: "discord", action: "Silenciar el micrófono", keys: ["Ctrl", "Shift", "M"] },
  { app: "discord", action: "Abrir el selector rápido", keys: ["Ctrl", "K"] },
  { app: "discord", action: "Ensordecer (silenciar audio)", keys: ["Ctrl", "Shift", "D"] },
  { app: "discord", action: "Marcar el servidor como leído", keys: ["Shift", "Esc"] },

  // ---- Gmail ----
  { app: "gmail", action: "Redactar un correo", keys: ["C"] },
  { app: "gmail", action: "Archivar la conversación", keys: ["E"] },
  { app: "gmail", action: "Responder a todos", keys: ["A"] },
  { app: "gmail", action: "Enviar el correo", keys: ["Ctrl", "Enter"] },

  // ---- YouTube ----
  { app: "youtube", action: "Pausar / reproducir", keys: ["K"], alt: [["Space"]] },
  { app: "youtube", action: "Adelantar 10 segundos", keys: ["L"] },
  { app: "youtube", action: "Retroceder 10 segundos", keys: ["J"] },
  { app: "youtube", action: "Silenciar el vídeo", keys: ["M"] },
  { app: "youtube", action: "Activar / desactivar subtítulos", keys: ["C"] },
  { app: "youtube", action: "Modo cine", keys: ["T"] },
];

SHORTCUTS.forEach((s, i) => { s.id = i; });
