// Base de datos de atajos (convención Windows/Linux; en Mac ⌘ cuenta como Ctrl).
// action: texto en español · en: texto en inglés.
// keys: combinación principal. alt: combinaciones alternativas que también se aceptan.

const APPS = {
  windows:   { name: "Windows",   icon: "🪟", cat: "Sistema", catEn: "System",      color: "#3A8DFF" },
  chrome:    { name: "Navegador", nameEn: "Browser", icon: "🌐", cat: "Internet", catEn: "Internet",     color: "#FFB020" },
  vscode:    { name: "VS Code",   icon: "🧑‍💻", cat: "Programación", catEn: "Programming", color: "#2D9CDB" },
  terminal:  { name: "Terminal",  icon: "🖥️", cat: "Programación", catEn: "Programming", color: "#3BD16F" },
  word:      { name: "Word",      icon: "📝", cat: "Ofimática", catEn: "Office",    color: "#2B6BE0" },
  excel:     { name: "Excel",     icon: "📊", cat: "Ofimática", catEn: "Office",    color: "#1E9E57" },
  photoshop: { name: "Photoshop", icon: "🎨", cat: "Diseño", catEn: "Design",       color: "#2FA3FF" },
  figma:     { name: "Figma",     icon: "✏️", cat: "Diseño", catEn: "Design",       color: "#A259FF" },
  discord:   { name: "Discord",   icon: "🎧", cat: "Comunicación", catEn: "Communication", color: "#5865F2" },
  gmail:     { name: "Gmail",     icon: "✉️", cat: "Comunicación", catEn: "Communication", color: "#EA4335" },
  youtube:   { name: "YouTube",   icon: "▶️", cat: "Multimedia", catEn: "Media",   color: "#FF2D2D" },
};

const SHORTCUTS = [
  // ---- Generales / Windows ----
  { app: "windows", action: "Copiar", en: "Copy", keys: ["Ctrl", "C"] },
  { app: "windows", action: "Pegar", en: "Paste", keys: ["Ctrl", "V"] },
  { app: "windows", action: "Cortar", en: "Cut", keys: ["Ctrl", "X"] },
  { app: "windows", action: "Deshacer", en: "Undo", keys: ["Ctrl", "Z"] },
  { app: "windows", action: "Rehacer", en: "Redo", keys: ["Ctrl", "Y"], alt: [["Ctrl", "Shift", "Z"]] },
  { app: "windows", action: "Seleccionar todo", en: "Select all", keys: ["Ctrl", "A"] },
  { app: "windows", action: "Guardar", en: "Save", keys: ["Ctrl", "S"] },
  { app: "windows", action: "Buscar en la página o documento", en: "Find in page or document", keys: ["Ctrl", "F"] },
  { app: "windows", action: "Imprimir", en: "Print", keys: ["Ctrl", "P"] },
  { app: "windows", action: "Cerrar la ventana activa", en: "Close the active window", keys: ["Alt", "F4"] },
  { app: "windows", action: "Cambiar entre ventanas abiertas", en: "Switch between open windows", keys: ["Alt", "Tab"] },
  { app: "windows", action: "Mostrar el escritorio", en: "Show the desktop", keys: ["Win", "D"] },
  { app: "windows", action: "Bloquear el equipo", en: "Lock the computer", keys: ["Win", "L"] },
  { app: "windows", action: "Abrir el Explorador de archivos", en: "Open File Explorer", keys: ["Win", "E"] },
  { app: "windows", action: "Recortar una captura de pantalla", en: "Snip a screenshot", keys: ["Win", "Shift", "S"] },
  { app: "windows", action: "Abrir el Administrador de tareas", en: "Open Task Manager", keys: ["Ctrl", "Shift", "Esc"] },
  { app: "windows", action: "Ver el historial del portapapeles", en: "View clipboard history", keys: ["Win", "V"] },
  { app: "windows", action: "Abrir el panel de emojis", en: "Open the emoji panel", keys: ["Win", "."], alt: [["Win", ";"]] },
  { app: "windows", action: "Abrir Configuración", en: "Open Settings", keys: ["Win", "I"] },
  { app: "windows", action: "Abrir el cuadro Ejecutar", en: "Open the Run dialog", keys: ["Win", "R"] },
  { app: "windows", action: "Renombrar el archivo seleccionado", en: "Rename the selected file", keys: ["F2"] },
  { app: "windows", action: "Ver propiedades del archivo", en: "View file properties", keys: ["Alt", "Enter"] },
  { app: "windows", action: "Crear un escritorio virtual nuevo", en: "Create a new virtual desktop", keys: ["Ctrl", "Win", "D"] },
  { app: "windows", action: "Maximizar la ventana", en: "Maximize the window", keys: ["Win", "↑"] },
  { app: "windows", action: "Anclar la ventana a la izquierda", en: "Snap the window to the left", keys: ["Win", "←"] },
  { app: "windows", action: "Eliminar sin pasar por la papelera", en: "Delete without using the Recycle Bin", keys: ["Shift", "Delete"] },
  { app: "windows", action: "Abrir la búsqueda de Windows", en: "Open Windows search", keys: ["Win", "S"] },
  { app: "windows", action: "Proyectar en otra pantalla", en: "Project to another screen", keys: ["Win", "P"] },
  { app: "windows", action: "Abrir la Xbox Game Bar", en: "Open the Xbox Game Bar", keys: ["Win", "G"] },
  { app: "windows", action: "Abrir el menú Inicio", en: "Open the Start menu", keys: ["Win"], alt: [["Ctrl", "Esc"]] },
  { app: "windows", action: "Captura de pantalla completa guardada", en: "Save a full-screen screenshot", keys: ["Win", "PrtSc"] },
  { app: "windows", action: "Minimizar todas las ventanas", en: "Minimize all windows", keys: ["Win", "M"] },

  // ---- Navegador ----
  { app: "chrome", action: "Abrir una pestaña nueva", en: "Open a new tab", keys: ["Ctrl", "T"] },
  { app: "chrome", action: "Reabrir la última pestaña cerrada", en: "Reopen the last closed tab", keys: ["Ctrl", "Shift", "T"] },
  { app: "chrome", action: "Cerrar la pestaña actual", en: "Close the current tab", keys: ["Ctrl", "W"], alt: [["Ctrl", "F4"]] },
  { app: "chrome", action: "Abrir una ventana de incógnito", en: "Open an incognito window", keys: ["Ctrl", "Shift", "N"] },
  { app: "chrome", action: "Ir a la pestaña siguiente", en: "Go to the next tab", keys: ["Ctrl", "Tab"], alt: [["Ctrl", "PgDn"]] },
  { app: "chrome", action: "Recargar ignorando la caché", en: "Reload ignoring the cache", keys: ["Ctrl", "Shift", "R"], alt: [["Ctrl", "F5"]] },
  { app: "chrome", action: "Abrir las herramientas para desarrolladores", en: "Open developer tools", keys: ["F12"], alt: [["Ctrl", "Shift", "I"]] },
  { app: "chrome", action: "Ver el historial", en: "View history", keys: ["Ctrl", "H"] },
  { app: "chrome", action: "Ver las descargas", en: "View downloads", keys: ["Ctrl", "J"] },
  { app: "chrome", action: "Seleccionar la barra de direcciones", en: "Focus the address bar", keys: ["Ctrl", "L"], alt: [["Alt", "D"], ["F6"]] },
  { app: "chrome", action: "Guardar la página en marcadores", en: "Bookmark the page", keys: ["Ctrl", "D"] },
  { app: "chrome", action: "Pantalla completa", en: "Full screen", keys: ["F11"] },
  { app: "chrome", action: "Restablecer el zoom", en: "Reset zoom", keys: ["Ctrl", "0"] },
  { app: "chrome", action: "Saltar a la última pestaña", en: "Jump to the last tab", keys: ["Ctrl", "9"] },
  { app: "chrome", action: "Ver el código fuente de la página", en: "View page source", keys: ["Ctrl", "U"] },
  { app: "chrome", action: "Recargar la página", en: "Reload the page", keys: ["F5"], alt: [["Ctrl", "R"]] },
  { app: "chrome", action: "Volver a la página anterior", en: "Go back to the previous page", keys: ["Alt", "←"] },

  // ---- VS Code ----
  { app: "vscode", action: "Abrir la paleta de comandos", en: "Open the command palette", keys: ["Ctrl", "Shift", "P"], alt: [["F1"]] },
  { app: "vscode", action: "Abrir un archivo rápidamente", en: "Quick open a file", keys: ["Ctrl", "P"] },
  { app: "vscode", action: "Comentar / descomentar la línea", en: "Toggle line comment", keys: ["Ctrl", "/"] },
  { app: "vscode", action: "Mostrar la terminal integrada", en: "Show the integrated terminal", keys: ["Ctrl", "`"] },
  { app: "vscode", action: "Mover la línea hacia arriba", en: "Move line up", keys: ["Alt", "↑"] },
  { app: "vscode", action: "Duplicar la línea hacia abajo", en: "Copy line down", keys: ["Shift", "Alt", "↓"] },
  { app: "vscode", action: "Seleccionar la siguiente coincidencia", en: "Select the next match", keys: ["Ctrl", "D"] },
  { app: "vscode", action: "Formatear el documento", en: "Format the document", keys: ["Shift", "Alt", "F"] },
  { app: "vscode", action: "Ir a la definición", en: "Go to definition", keys: ["F12"] },
  { app: "vscode", action: "Renombrar un símbolo", en: "Rename a symbol", keys: ["F2"] },
  { app: "vscode", action: "Mostrar / ocultar la barra lateral", en: "Toggle the sidebar", keys: ["Ctrl", "B"] },
  { app: "vscode", action: "Añadir un cursor en la línea de arriba", en: "Add a cursor on the line above", keys: ["Ctrl", "Alt", "↑"] },
  { app: "vscode", action: "Eliminar la línea completa", en: "Delete the whole line", keys: ["Ctrl", "Shift", "K"] },
  { app: "vscode", action: "Ir a una línea concreta", en: "Go to a specific line", keys: ["Ctrl", "G"] },
  { app: "vscode", action: "Buscar en todos los archivos", en: "Search across all files", keys: ["Ctrl", "Shift", "F"] },
  { app: "vscode", action: "Dividir el editor", en: "Split the editor", keys: ["Ctrl", "\\"] },

  // ---- Terminal ----
  { app: "terminal", action: "Interrumpir el proceso en ejecución", en: "Interrupt the running process", keys: ["Ctrl", "C"] },
  { app: "terminal", action: "Limpiar la pantalla", en: "Clear the screen", keys: ["Ctrl", "L"] },
  { app: "terminal", action: "Buscar en el historial de comandos", en: "Search command history", keys: ["Ctrl", "R"] },
  { app: "terminal", action: "Ir al inicio de la línea", en: "Go to the start of the line", keys: ["Ctrl", "A"], alt: [["Home"]] },
  { app: "terminal", action: "Enviar fin de archivo (EOF) / salir", en: "Send end-of-file (EOF) / exit", keys: ["Ctrl", "D"] },
  { app: "terminal", action: "Autocompletar el comando", en: "Autocomplete the command", keys: ["Tab"] },
  { app: "terminal", action: "Suspender el proceso", en: "Suspend the process", keys: ["Ctrl", "Z"] },
  { app: "terminal", action: "Borrar la palabra anterior", en: "Delete the previous word", keys: ["Ctrl", "W"] },

  // ---- Word ----
  { app: "word", action: "Poner el texto en negrita", en: "Make text bold", keys: ["Ctrl", "B"], alt: [["Ctrl", "N"]] },
  { app: "word", action: "Poner el texto en cursiva", en: "Make text italic", keys: ["Ctrl", "I"], alt: [["Ctrl", "K"]] },
  { app: "word", action: "Subrayar el texto", en: "Underline text", keys: ["Ctrl", "U"], alt: [["Ctrl", "S"]] },
  { app: "word", action: "Centrar el párrafo", en: "Center the paragraph", keys: ["Ctrl", "E"], alt: [["Ctrl", "T"]] },
  { app: "word", action: "Justificar el párrafo", en: "Justify the paragraph", keys: ["Ctrl", "J"] },
  { app: "word", action: "Insertar un salto de página", en: "Insert a page break", keys: ["Ctrl", "Enter"] },
  { app: "word", action: "Aumentar el tamaño de la fuente", en: "Increase font size", keys: ["Ctrl", "Shift", "."], alt: [["Ctrl", "]"]] },
  { app: "word", action: "Revisar la ortografía", en: "Check spelling", keys: ["F7"] },
  { app: "word", action: "Alternar mayúsculas / minúsculas", en: "Toggle uppercase / lowercase", keys: ["Shift", "F3"] },

  // ---- Excel ----
  { app: "excel", action: "Insertar la fecha de hoy", en: "Insert today's date", keys: ["Ctrl", ";"] },
  { app: "excel", action: "Autosuma", en: "AutoSum", keys: ["Alt", "="] },
  { app: "excel", action: "Editar la celda activa", en: "Edit the active cell", keys: ["F2"] },
  { app: "excel", action: "Crear una tabla", en: "Create a table", keys: ["Ctrl", "T"], alt: [["Ctrl", "Q"]] },
  { app: "excel", action: "Ocultar las filas seleccionadas", en: "Hide the selected rows", keys: ["Ctrl", "9"] },
  { app: "excel", action: "Saltar al final de los datos hacia abajo", en: "Jump to the bottom of the data", keys: ["Ctrl", "↓"] },
  { app: "excel", action: "Abrir Formato de celdas", en: "Open Format Cells", keys: ["Ctrl", "1"] },
  { app: "excel", action: "Fijar referencia absoluta ($A$1)", en: "Toggle absolute reference ($A$1)", keys: ["F4"] },
  { app: "excel", action: "Insertar una hoja nueva", en: "Insert a new sheet", keys: ["Shift", "F11"] },
  { app: "excel", action: "Insertar un hipervínculo", en: "Insert a hyperlink", keys: ["Ctrl", "K"] },
  { app: "excel", action: "Activar / desactivar filtros", en: "Toggle filters", keys: ["Ctrl", "Shift", "L"] },

  // ---- Photoshop ----
  { app: "photoshop", action: "Transformación libre", en: "Free transform", keys: ["Ctrl", "T"] },
  { app: "photoshop", action: "Crear una capa nueva", en: "Create a new layer", keys: ["Ctrl", "Shift", "N"] },
  { app: "photoshop", action: "Deseleccionar", en: "Deselect", keys: ["Ctrl", "D"] },
  { app: "photoshop", action: "Invertir la selección", en: "Invert the selection", keys: ["Ctrl", "Shift", "I"] },
  { app: "photoshop", action: "Duplicar la capa", en: "Duplicate the layer", keys: ["Ctrl", "J"] },
  { app: "photoshop", action: "Herramienta Pincel", en: "Brush tool", keys: ["B"] },
  { app: "photoshop", action: "Herramienta Mover", en: "Move tool", keys: ["V"] },
  { app: "photoshop", action: "Ajustar la imagen a la pantalla", en: "Fit image on screen", keys: ["Ctrl", "0"] },
  { app: "photoshop", action: "Combinar las capas visibles", en: "Merge visible layers", keys: ["Ctrl", "Shift", "E"] },

  // ---- Figma ----
  { app: "figma", action: "Agrupar la selección", en: "Group the selection", keys: ["Ctrl", "G"] },
  { app: "figma", action: "Crear un componente", en: "Create a component", keys: ["Ctrl", "Alt", "K"] },
  { app: "figma", action: "Añadir Auto layout", en: "Add auto layout", keys: ["Shift", "A"] },
  { app: "figma", action: "Herramienta Rectángulo", en: "Rectangle tool", keys: ["R"] },
  { app: "figma", action: "Mostrar / ocultar la interfaz", en: "Show / hide the UI", keys: ["Ctrl", "\\"] },
  { app: "figma", action: "Zoom para ver todo", en: "Zoom to fit all", keys: ["Shift", "1"] },
  { app: "figma", action: "Herramienta Texto", en: "Text tool", keys: ["T"] },

  // ---- Discord ----
  { app: "discord", action: "Silenciar el micrófono", en: "Mute the microphone", keys: ["Ctrl", "Shift", "M"] },
  { app: "discord", action: "Abrir el selector rápido", en: "Open the quick switcher", keys: ["Ctrl", "K"] },
  { app: "discord", action: "Ensordecer (silenciar audio)", en: "Deafen (mute audio)", keys: ["Ctrl", "Shift", "D"] },
  { app: "discord", action: "Marcar el servidor como leído", en: "Mark the server as read", keys: ["Shift", "Esc"] },

  // ---- Gmail ----
  { app: "gmail", action: "Redactar un correo", en: "Compose an email", keys: ["C"] },
  { app: "gmail", action: "Archivar la conversación", en: "Archive the conversation", keys: ["E"] },
  { app: "gmail", action: "Responder a todos", en: "Reply all", keys: ["A"] },
  { app: "gmail", action: "Enviar el correo", en: "Send the email", keys: ["Ctrl", "Enter"] },

  // ---- YouTube ----
  { app: "youtube", action: "Pausar / reproducir", en: "Pause / play", keys: ["K"], alt: [["Space"]] },
  { app: "youtube", action: "Adelantar 10 segundos", en: "Skip forward 10 seconds", keys: ["L"] },
  { app: "youtube", action: "Retroceder 10 segundos", en: "Rewind 10 seconds", keys: ["J"] },
  { app: "youtube", action: "Silenciar el vídeo", en: "Mute the video", keys: ["M"] },
  { app: "youtube", action: "Activar / desactivar subtítulos", en: "Toggle captions", keys: ["C"] },
  { app: "youtube", action: "Modo cine", en: "Theater mode", keys: ["T"] },
];

SHORTCUTS.forEach((s, i) => { s.id = i; });
